In [190]:
#importing necessary libraries
import selenium
import pandas as pd
from bs4 import BeautifulSoup
import time

#Importing requests
import requests

# importing regex
import re

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait

import warnings
warnings.filterwarnings('ignore')

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia:Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [38]:
#Let's first connect to the webdriver
driver=webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [39]:
#getting the specified the url
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(3)

In [40]:
#Creating empty list
Rank = []
Name = []
Artist = []
Upload_date = []
Views = []

In [41]:
#scraping the data of rank
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[1]")[:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')

In [42]:
#Scraping data of video names
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[2]")[:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

In [43]:
#Scraping data of artist name
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[3]")[:30]:
        Artist.append(i.text)
except NoSuchElementException:        
    Artist.append('-')

In [44]:
#Scraping data of upload dates
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[5]")[:30]:
        Upload_date.append(i.text)
except NoSuchElementException:        
    Upload_date.append('-')

In [45]:
#Scraping data of views
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[4]")[:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append('-')

In [46]:
#DATA FRAMEING
Youtube=pd.DataFrame({})
Youtube['Rank'] = Rank
Youtube['Name'] = Name
Youtube['Artist'] = Artist
Youtube['Uploaded Date'] = Upload_date
Youtube['Views'] = Views

In [47]:
#Printing data frame
Youtube

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.18
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.74
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.16
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.61
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.41
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.97
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,8.,"""Masha and the Bear – Recipe for Disaster""[22]",Get Movies,"January 31, 2012",4.48
8,9.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",4.46
9,10.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.46
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.34
11,12.,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.84
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.66
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.64
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.52
15,16.,"""Sorry""[34]",Justin Bieber,"October 22, 2015",3.51
16,17.,"""Counting Stars""[35]",OneRepublic,"May 31, 2013",3.51
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.40
18,19.,"""Girls Like You""[37]",Maroon 5,"May 31, 2018",3.23
19,20.,"""Faded""[38]",Alan Walker,"December 3, 2015",3.23
20,21.,"""Dark Horse""[39]",Katy Perry,"February 20, 2014",3.22
21,22.,"""Axel F""[40]",Crazy Frog,"June 16, 2009",3.22
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.17
23,24.,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.16
24,25.,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.16
25,26.,"""Shake It Off""[44]",Taylor Swift,"August 18, 2014",3.14
26,27.,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.12
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.09
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.06
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.04

# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details:
A) Name
B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [8]:
# Connecting to the webdriver
driver =webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [9]:
#getting the specified url
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(3)

In [11]:
#Going to search bar and searching for selenium exception
ser_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
ser_bar.send_keys("selenium exception handling")
ser_but = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click()
time.sleep(3)

In [12]:
#Url of selenium exception handling page
urls = driver.find_element_by_xpath("//div[@class='gsc-expansionArea']//div//a")
page_url = urls.get_attribute("href")

driver.get(page_url)
time.sleep(5)

#Scraping data of names of exceptions
Name = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[1]")[1:]:
    Name.append(i.text)
    
#Scraping data of descriptions of exceptions  
Description = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[2]")[1:]:
    Description.append(i.text)

In [13]:
#DATA FRAMEING
Guru=pd.DataFrame({})
Guru['Name of Exception'] = Name
Guru['Description of Exception'] = Description

In [14]:
#Printing data frame
Guru

,Name of Exception,Description of Exception
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:

A) Rank

B) State

C) GSDP

D) GSDP

E) Share

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [15]:
# Connecting to the webdriver
driver =webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [16]:
#getting the specified url
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(3)

In [17]:
#Clicking on economy section
economy = driver.find_element_by_xpath("//div[@class='navbar']//div[2]//button").click()

urls = driver.find_element_by_xpath("//div[@class='dropdown-content']//a[3]")
ineco_page = urls.get_attribute("href")
#Going to indian economy page
driver.get(ineco_page)  
time.sleep(5)

In [20]:
#Creating empty list
Rank = []
State = []
GSDP_1 = []
GSDP_2 = []
Share = []
GDP = []

In [21]:
#get the url of page containing GDP of indian states
sta_GDP = driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a")
GDP_url = sta_GDP.get_attribute("href")

driver.get(GDP_url)
time.sleep(6)


#Scraping data of rank
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[1]"):
    Rank.append(i.text)

    
#Scraping data of state name
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[2]"):
    State.append(i.text)

    
# Scraping data of GSDP at current price
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[3]"):
    GSDP_1.append(i.text)

    
#Scraping data of GSDP at current price
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[4]"):
    GSDP_2.append(i.text)

    
#Scraping data of Share
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[5]"):
    Share.append(i.text)

    
#Scraping data of GDP($ billion)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[6]"):
    GDP.append(i.text)

In [22]:
#DATA FRAMEING
StatisticsTime=pd.DataFrame({})
StatisticsTime['Rank'] = Rank
StatisticsTime['State'] = State
StatisticsTime['GSDP at current price'] = GSDP_1
StatisticsTime['GSDP at current price'] = GSDP_2
StatisticsTime['Share'] = Share
StatisticsTime['GDP($ billion)'] = GDP

In [23]:
#Printing the data frame
StatisticsTime

,Rank,State,GSDP at current price,Share,GDP($ billion)
0,1,Maharashtra,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764",8.39%,240.726
3,4,Gujarat,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,493,127",7.91%,226.806
5,6,West Bengal,"1,089,898",5.77%,165.556
6,7,Rajasthan,"942,586",4.99%,143.179
7,8,Andhra Pradesh,"862,957",4.57%,131.083
8,9,Telangana,"861,031",4.56%,130.791
9,10,Madhya Pradesh,"809,592",4.29%,122.977
10,11,Kerala,"781,653",4.14%,118.733
11,12,Delhi,"774,870",4.10%,117.703
12,13,Haryana,"734,163",3.89%,111.519
13,14,Bihar,"530,363",2.81%,80.562
14,15,Punjab,"526,376",2.79%,79.957
15,16,Odisha,"487,805",2.58%,74.098
16,17,Assam,"315,881",1.67%,47.982
17,18,Chhattisgarh,"304,063",1.61%,46.187
18,19,Jharkhand,"297,204",1.57%,45.145
19,20,Uttarakhand,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"153,845",0.81%,23.369
22,23,Goa,"73,170",0.39%,11.115
23,24,Tripura,"49,845",0.26%,7.571
24,25,Chandigarh,"42,114",0.22%,6.397
25,26,Puducherry,"34,433",0.18%,5.230
26,27,Meghalaya,"33,481",0.18%,5.086
27,28,Sikkim,"28,723",0.15%,4.363
28,29,Manipur,"27,870",0.15%,4.233
29,30,Nagaland,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,"24,603",0.13%,3.737
31,32,Mizoram,"22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [45]:
# Connecting to the webdriver
driver =webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [46]:
#getting the specified url
url = "https://github.com/"
driver.get(url)
time.sleep(3)

In [47]:
#Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary").click()

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [48]:
#Creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

    
# Scraping Repository Title data
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

    
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(3)
    
    
    # Scraping Repository Description data
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # Scraping Contributors Count data
    try:
        contributor = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        # Scraping Languages used data
    try:
        for i in driver.find_elements_by_xpath("//a[@class='topic-tag topic-tag-link']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')
        
#DATA FRAMEING
Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,BishopFox / unredacter,Never ever ever use pixelation as a redaction ...,2,"[java, redis, elasticsearch, distributed-syste..."
1,alibaba / lowcode-engine,-,5,"[java, redis, elasticsearch, distributed-syste..."
2,doocs / advanced-java,😮 Core Interview Questions & Answers For Exper...,31,"[java, redis, elasticsearch, distributed-syste..."
3,qiurunze123 / miaosha,⭐⭐⭐⭐秒杀系统设计与实现.互联网工程师进阶与分析🙋🐓,7,"[java, redis, elasticsearch, distributed-syste..."
4,saadeghi / daisyui,⭐️ ⭐️ ⭐️ ⭐️ ⭐️ Tailwind Components,26,"[java, redis, elasticsearch, distributed-syste..."
5,filecoin-project / lotus,"Implementation of the Filecoin protocol, writt...",146,"[java, redis, elasticsearch, distributed-syste..."
6,Anduin2017 / HowToCook,程序员在家做饭方法指南。,27,"[java, redis, elasticsearch, distributed-syste..."
7,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,112,"[java, redis, elasticsearch, distributed-syste..."
8,DataTalksClub / data-engineering-zoomcamp,Free Data Engineering course!,27,"[java, redis, elasticsearch, distributed-syste..."
9,quenhus / uBlock-Origin-dev-filter,Filters to block and remove copycat-websites f...,14,"[java, redis, elasticsearch, distributed-syste..."
10,algorithmica-org / algorithmica,New version of the website,31,"[java, redis, elasticsearch, distributed-syste..."
11,csguide-dabai / Programmer-look-at-China,介绍中国各二线以上城市的互联网环境以及生活成本,2,"[java, redis, elasticsearch, distributed-syste..."
12,OffcierCia / DeFi-Developer-Road-Map,DeFi Developer roadmap is a curated Web3.0 Dev...,18,"[java, redis, elasticsearch, distributed-syste..."
13,dair-ai / GNNs-Recipe,A recipe to study Graph Neural Networks (GNNs),2,"[java, redis, elasticsearch, distributed-syste..."
14,LSPosed / MagiskOnWSA,Integrate Magisk root and Google Apps (OpenGAp...,14,"[java, redis, elasticsearch, distributed-syste..."
15,odin-lang / Odin,Odin Programming Language,93,"[java, redis, elasticsearch, distributed-syste..."
16,google / googletest,GoogleTest - Google Testing and Mocking Framework,352,"[java, redis, elasticsearch, distributed-syste..."
17,probml / pml-book,"""Probabilistic Machine Learning"" - a book seri...",2,"[java, redis, elasticsearch, distributed-syste..."
18,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,394","[java, redis, elasticsearch, distributed-syste..."
19,evanw / esbuild,An extremely fast JavaScript and CSS bundler a...,78,"[java, redis, elasticsearch, distributed-syste..."
20,obss / sahi,A lightweight vision library for performing la...,8,"[java, redis, elasticsearch, distributed-syste..."
21,laravel / framework,The Laravel Framework.,"2,735","[java, redis, elasticsearch, distributed-syste..."
22,libevent / libevent,Event notification library,196,"[java, redis, elasticsearch, distributed-syste..."
23,littlefs-project / littlefs,A little fail-safe filesystem designed for mic...,32,"[java, redis, elasticsearch, distributed-syste..."
24,mqyqingfeng / Blog,冴羽写博客的地方，预计写四个系列：JavaScript深入系列、JavaScript专题系列...,2,"[java, redis, elasticsearch, distributed-syste..."

# 6: Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/
You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [191]:
# Connecting to the webdriver
driver = webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [192]:
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(6)
driver.maximize_window()

In [203]:
time.sleep(3)
Hot_song= driver.find_element_by_xpath("//li[@class='o-nav__list-item ']//a")
Hot_song.click()
time.sleep(3)

In [204]:
# Creating Blank List
Song_name=[]
Artist_name=[]
Last_week_rank=[]
Peak_rank=[]
Weeks_on_board=[]

In [205]:
#Scraping Song_name
song_name= driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[1]")
for i in song_name:
    if i.text is None:
        Song_name.append('--')
    else:
        Song_name.append(i.text)

In [206]:
#Scraping Artist_name
artist_name= driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[2]")
for i in artist_name:
    if i.text is None:
        Artist_name.append('--')
    else:
        Artist_name.append(i.text)

In [207]:
#Scraping Last_week_rank
last_week_rank= driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
for i in last_week_rank:
    if i.text is None:
        Last_week_rank.append('--')
    else:
        Last_week_rank.append(i.text)
        
#Scraping Peak_rank
peak_rank= driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
for i in peak_rank:
    if i.text is None:
        Peak_rank.append('--')
    else:
        Peak_rank.append(i.text)
        
#Scraping Weeks_on_board
weeks_on_board= driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for i in weeks_on_board:
    if i.text is None:
        Weeks_on_board.append('--')
    else:
        Weeks_on_board.append(i.text)

Hot_Songs=pd.DataFrame({})
Hot_Songs['Song_name']=Song_name
Hot_Songs['Artist_name']=Artist_name
Hot_Songs['Last_week_rank']=Last_week_rank
Hot_Songs['Peak_rank']=Peak_rank
Hot_Songs['Weeks_on_board']=Weeks_on_board

Hot_Songs

Empty DataFrame
Columns: [Song_name, Artist_name, Last_week_rank, Peak_rank, Weeks_on_board]
Index: []

# 7: Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [80]:
# Connecting to the webdriver
driver = webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.naukri.com/naukri-dot-com-recruiters')
driver.get(url)
time.sleep(2)

In [81]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [82]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()     
time.sleep(3)

In [83]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(3)

#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(3)
    
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(3)

#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[:50]
Naukri['Designation'] = Designation[:50]
Naukri['Company'] = Company[:50]
Naukri['Skills'] = Skills[:50]
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",subhas patel
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",UK - (london)
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Recruitment Lead Consultant
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Vadodara / Baroda
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Trivandrum
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Asif Lucknowi
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Director
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Indore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",InstaFinancials
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Human Resource
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Sakshi Chhikara
31,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Assistant Manager HR
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Chandigarh
33,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Priyanka Akiri
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",HR Manager
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Kalpana Dumpala
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Executive Hiring
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Hyderabad / Secunderabad
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mubarak
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Kushal Rastogi
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Company HR
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Mumbai
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mahesh Babu Channa
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",HR Team Lead
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Hyderabad / Secunderabad
48,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Kapil Devang
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",HR Manager

# 8: Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [84]:
# Connecting to the webdriver
driver = webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [85]:
# Getting the webpage of mentioned url 
url=('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')
driver.get(url)

In [86]:
#Creating empty list
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

#scraping book names data
for i in driver.find_elements_by_xpath("//tbody//tr/td[2]"):
    Book_name.append(i.text)

    
#Scraping author names data
for i in driver.find_elements_by_xpath("//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(1)


#Scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

    
#Scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody/tr/td[5]"):
    Publisher.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//tbody/tr/td[6]"):
    Genre.append(i.text)
    
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9: Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [87]:
# Connecting to the webdriver
driver = webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [88]:
# Getting the webpage of mentioned url 
url=("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [89]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)

#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)
    
# Creating dataframe for scraped data
TV_series=pd.DataFrame({})
TV_series['Name'] = Name
TV_series['Year Span'] = Year_span
TV_series['Genre'] = Genre
TV_series['Run Time'] = Run_time
TV_series['Ratings'] = Ratings
TV_series['Votes'] = Votes
TV_series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,956,271"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"966,073"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"931,823"
3,13 Reasons Why,(2017– ),"Drama, Mystery, Thriller",60 min,7.5,"278,998"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"239,169"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,789"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,514"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"185,700"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,311"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"221,979"

# 10: Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code

In [90]:
# Connecting to the webdriver
driver = webdriver.Chrome(r'C:\Users\Chandru\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [91]:
# Getting the webpage of mentioned url 
url=("https://archive.ics.uci.edu/")
driver.get(url)

In [92]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(3)

In [93]:
# Fetching page urls of all datasets 
view_list = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)
time.sleep(3)

In [94]:
# Fetching urls for each dataset
dataset_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [96]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

for i in urls:
    driver.get(i)
    time.sleep(3)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element_by_xpath("//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    time.sleep(2)
    
    #Scraping data type
    try:
        data_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(2)
    
    #scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(2)
    
    # Scraping Attribute type
    try:
        attribute_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    time.sleep(2)
    
    # Scraping No of instances
    try:
        instances = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    time.sleep(2)
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    time.sleep(2)
    
    # Scraping year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(2)

In [97]:
# Creating dataframe for scraped data
ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name
ML['Data Type'] = Data_type
ML['Task'] = Task
ML['Attribute type'] = Attribute_type
ML['No of instance'] = No_of_instances
ML['No of attributes'] = No_of_attributes
ML['Year'] = Year
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990